export const BUSINESS_RULES = {
  GPS_STALE_MINUTES: 5,
  SPEEDING_THRESHOLD_KMH: 80,
  MAINTENANCE_ODOMETER_INTERVAL_KM: 10000,
}

export const FLEET_REFRESH_INTERVAL_MS = 30000

export const TOAST_DURATION_MS = 4500
