export const ROLES = {
  GUEST: 'GUEST',
  DRIVER: 'DRIVER',
  MAINTENANCE_MANAGER: 'MAINTENANCE_MANAGER',
  LOGISTICS_COORDINATOR: 'LOGISTICS_COORDINATOR',
  FLEET_MANAGER: 'FLEET_MANAGER',
  FINANCE_OFFICER: 'FINANCE_OFFICER',
  SYSTEM_ADMINISTRATOR: 'SYSTEM_ADMINISTRATOR',
}

export const ROLE_LABELS = {
  GUEST: 'Guest',
  DRIVER: 'Driver',
  MAINTENANCE_MANAGER: 'Maintenance Manager',
  LOGISTICS_COORDINATOR: 'Logistics Coordinator',
  FLEET_MANAGER: 'Fleet Manager',
  FINANCE_OFFICER: 'Finance Officer',
  SYSTEM_ADMINISTRATOR: 'System Administrator',
}

export const ROLE_SHORT_LABELS = {
  GUEST: 'Guest',
  DRIVER: 'Driver',
  MAINTENANCE_MANAGER: 'Maintenance',
  LOGISTICS_COORDINATOR: 'Logistics',
  FLEET_MANAGER: 'Fleet Manager',
  FINANCE_OFFICER: 'Finance',
  SYSTEM_ADMINISTRATOR: 'Administrator',
}

export const ALL_ROLES = Object.values(ROLES)

export const REGISTRABLE_ROLES = [
  ROLES.DRIVER,
  ROLES.MAINTENANCE_MANAGER,
  ROLES.LOGISTICS_COORDINATOR,
  ROLES.FLEET_MANAGER,
  ROLES.FINANCE_OFFICER,
]
